/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type CustomHtml = {
  _type: "custom-html";
  codeTitle?: string;
  html?: Code;
  isAddFiles?: boolean;
  fileGroup?: Array<{
    title?: string;
    files?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      _type: "file";
      _key: string;
    }>;
    _key: string;
  }>;
};

export type CreationArchives = {
  _type: "creationArchives";
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  archive?: Array<{
    title?: string;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    status?: string;
    _key: string;
  }>;
};

export type LastEvent = {
  _type: "lastEvent";
  event?: {
    isDisplayed?: boolean;
    title?: string;
    events?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "events";
    }>;
    ctaToEvents?: string;
  };
};

export type ContactForm = {
  _type: "contact-form";
  title?: string;
  description?: string;
  recipient?: string;
};

export type Link = {
  _type: "link";
  label?: string;
  type?: "internal" | "external" | "mail";
  internal?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "pages";
  };
  external?: string;
  mail?: string;
};

export type MultiImages = {
  _type: "multi-images";
  title?: string;
  images?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
    _key: string;
  }>;
};

export type SingleImage = {
  _type: "single-image";
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type DocumentFile = {
  _type: "document-file";
  title?: string;
  file?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
};

export type RichTextAndTitle = {
  _type: "richTextAndTitle";
  title?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Richtext = {
  _type: "richtext";
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Content = {
  _type: "content";
  isLink?: boolean;
  titleBlock?: string;
  block?: Array<
    | ({
        _key: string;
      } & ContactForm)
    | ({
        _key: string;
      } & CreationArchives)
    | ({
        _key: string;
      } & CustomHtml)
    | ({
        _key: string;
      } & DocumentFile)
    | ({
        _key: string;
      } & LastEvent)
    | ({
        _key: string;
      } & Link)
    | ({
        _key: string;
      } & MultiImages)
    | ({
        _key: string;
      } & SingleImage)
    | ({
        _key: string;
      } & Richtext)
    | ({
        _key: string;
      } & RichTextAndTitle)
  >;
};

export type Blogs = {
  _id: string;
  _type: "blogs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  blogTitle?: string;
  slug?: Slug;
  blogContentText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  blogImages?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
    _key: string;
  }>;
};

export type Events = {
  _id: string;
  _type: "events";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eventType?: string;
  eventTitle?: string;
  eventEntrance?: string;
  eventDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  eventDate?: {
    eventStartDate?: string;
    addEndDate?: boolean;
    eventEndDate?: string;
  };
  eventLocation?: string;
  eventImage?: {
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
  };
};

export type LesArchivesVivantes = {
  _id: string;
  _type: "lesArchivesVivantes";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  linkToVimeo?: string;
  linkToPodcast?: string;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    hero?: Array<{
      title?: string;
      paragraph?: string;
      image?: {
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt?: string;
      };
      cta?: {
        ctaLabel?: string;
        ctaLink?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "pages";
        };
      };
      _key: string;
    }>;
  };
  secondPart?: {
    block?: Array<{
      title?: string;
      paragraph?: string;
      image?: {
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt?: string;
      };
      cta?: {
        ctaLabel?: string;
        ctaLink?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "pages";
        };
      };
      _key: string;
    }>;
  };
  video?: {
    videoTitle?: string;
    videoLink?: string;
  };
  outro?: {
    outroTitle?: string;
    outroText?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  };
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  globalSettings?: {
    siteTitle?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  header?: {
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    headerLinks?: Array<{
      type?: "internal" | "external";
      linkPosition?: "left" | "right";
      internalLink?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "pages";
      };
      externalLink?: {
        title?: string;
        url?: string;
      };
      _key: string;
    }>;
  };
  footer?: {
    moduleGroups?: Array<{
      groupName?: string;
      modules?: Array<{
        type?: "internal" | "external" | "text";
        internalLink?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "pages";
        };
        externalLink?: {
          title?: string;
          url?: string;
        };
        text?: string;
        _key: string;
      }>;
      _key: string;
    }>;
  };
};

export type Pages = {
  _id: string;
  _type: "pages";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: Array<
    {
      _key: string;
    } & Content
  >;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | CustomHtml
  | CreationArchives
  | LastEvent
  | ContactForm
  | Link
  | MultiImages
  | SingleImage
  | DocumentFile
  | RichTextAndTitle
  | Richtext
  | Content
  | Blogs
  | Events
  | LesArchivesVivantes
  | Homepage
  | Settings
  | Pages
  | SanityFileAsset
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | MediaTag
  | Slug
  | Code;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0] {  "globalSettings": {    "siteTitle": globalSettings.siteTitle,    "ogImage": globalSettings.ogImage.asset->url,    "altText": globalSettings.ogImage.alt,    "svg": globalSettings.svgIcon,  },  "header": {    "logo": header.logo.asset->url,    "links": header.headerLinks[] {      _key,      type,      linkPosition,      "internalLinkDetails": internalLink-> {        _id,        _key,        _type,        title,        "slug": slug.current      },      "externalLinkDetails": {        _key,        "title": externalLink.title,        "url": externalLink.url      }    }  },  "footer": {    _id,    "moduleGroups": footer.moduleGroups[] {      _id,      _key,      groupName,      "modules": modules[] {        _key,        _id,        type,        "internalDetails": internalLink-> {          _key,          _id,          _type,          title,          "slug": slug.current        },        "externalDetails": {          "title": externalLink.title,          "url": externalLink.url        },        "text": text      }    }  }}
export type SettingsQueryResult = {
  globalSettings: {
    siteTitle: string | null;
    ogImage: string | null;
    altText: string | null;
    svg: null;
  };
  header: {
    logo: string | null;
    links: Array<{
      _key: string;
      type: "external" | "internal" | null;
      linkPosition: "left" | "right" | null;
      internalLinkDetails: {
        _id: string;
        _key: null;
        _type: "pages";
        title: string | null;
        slug: string | null;
      } | null;
      externalLinkDetails: {
        _key: string;
        title: string | null;
        url: string | null;
      };
    }> | null;
  };
  footer: {
    _id: string;
    moduleGroups: Array<{
      _id: null;
      _key: string;
      groupName: string | null;
      modules: Array<{
        _key: string;
        _id: null;
        type: "external" | "internal" | "text" | null;
        internalDetails: {
          _key: null;
          _id: string;
          _type: "pages";
          title: string | null;
          slug: string | null;
        } | null;
        externalDetails: {
          title: string | null;
          url: string | null;
        };
        text: string | null;
      }> | null;
    }> | null;
  };
} | null;
// Variable: moreStoriesQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {    _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},}
export type MoreStoriesQueryResult = Array<never>;
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {  content,    _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},}
export type PostQueryResult = null;
// Variable: headerQuery
// Query: *[_type == "header"] {  "imageUrl": logo.asset->url,  "url": links[]->{     title,     "slug": slug.current  }}
export type HeaderQueryResult = Array<never>;
// Variable: footerQuery
// Query: *[_type == "footer"][0] {  title,}
export type FooterQueryResult = null;
// Variable: heroQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) [0] {  content,    _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},}
export type HeroQueryResult = null;
// Variable: homepageQuery
// Query: *[_type == "homepage"][0] {  _key,  _id,  _type,  "hero": hero.hero[]{      ...,  _id,  _key,  "image": image{    "imageUrl": image.asset->url,    alt,  },  cta {    ctaLabel,    ctaLink->{      _type,      "slug": slug.current    }  },  },  "secondPart": secondPart.block[]{     ...,  _id,  _key,  "image": image{    "imageUrl": image.asset->url,    alt,  },  cta {    ctaLabel,    ctaLink->{      _type,      "slug": slug.current    }  },  },  video {    videoTitle,    videoLink,  },  outro {    outroTitle,    outroText,  },}
export type HomepageQueryResult = {
  _key: null;
  _id: string;
  _type: "homepage";
  hero: Array<{
    title?: string;
    paragraph?: string;
    image: {
      imageUrl: string | null;
      alt: string | null;
    } | null;
    cta: {
      ctaLabel: string | null;
      ctaLink: {
        _type: "pages";
        slug: string | null;
      } | null;
    } | null;
    _key: string;
    _id: null;
  }> | null;
  secondPart: Array<{
    title?: string;
    paragraph?: string;
    image: {
      imageUrl: string | null;
      alt: string | null;
    } | null;
    cta: {
      ctaLabel: string | null;
      ctaLink: {
        _type: "pages";
        slug: string | null;
      } | null;
    } | null;
    _key: string;
    _id: null;
  }> | null;
  video: {
    videoTitle: string | null;
    videoLink: string | null;
  } | null;
  outro: {
    outroTitle: string | null;
    outroText: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
} | null;
// Variable: eventsQuery
// Query: *[_type == "events" ] | order(eventDate.eventStartDate desc) {  _id,  eventTitle,  slug,  eventDate,  eventDescription,  eventLocation,  "image": eventImage{    "imageUrl": image.asset->url,    alt,  },}
export type EventsQueryResult = Array<{
  _id: string;
  eventTitle: string | null;
  slug: null;
  eventDate: {
    eventStartDate?: string;
    addEndDate?: boolean;
    eventEndDate?: string;
  } | null;
  eventDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  eventLocation: string | null;
  image: {
    imageUrl: string | null;
    alt: string | null;
  } | null;
}>;
// Variable: eventQuery
// Query: *[_type == "events" && slug.current == $event][0]{  _id,  eventTitle,  slug,  eventDate,  eventDescription,  eventLocation,  "image": eventImage{      "imageUrl": image.asset->url,      alt,    },}
export type EventQueryResult = {
  _id: string;
  eventTitle: string | null;
  slug: null;
  eventDate: {
    eventStartDate?: string;
    addEndDate?: boolean;
    eventEndDate?: string;
  } | null;
  eventDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  eventLocation: string | null;
  image: {
    imageUrl: string | null;
    alt: string | null;
  } | null;
} | null;
// Variable: lastEventQuery
// Query: *[_type == "events" && defined(eventDate) && eventDate.eventStartDate >= now()] | order(eventDate.eventDateStart asc) [0...5] {  _id,  eventTitle,  slug,  eventDate,  eventDescription,  eventLocation,  "image": eventImage{    "imageUrl": image.asset->url,    alt,  },}
export type LastEventQueryResult = Array<{
  _id: string;
  eventTitle: string | null;
  slug: null;
  eventDate: {
    eventStartDate?: string;
    addEndDate?: boolean;
    eventEndDate?: string;
  } | null;
  eventDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  eventLocation: string | null;
  image: {
    imageUrl: string | null;
    alt: string | null;
  } | null;
}>;
// Variable: blogsQuery
// Query: *[_type == "blogs" ] | order(eventDate.eventStartDate desc) {  _id,  blogTitle,  slug,  blogContentText,  "blogImages": blogImages[] {    "imageUrl": image.asset->url,    alt,  },}
export type BlogsQueryResult = Array<{
  _id: string;
  blogTitle: string | null;
  slug: Slug | null;
  blogContentText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  blogImages: Array<{
    imageUrl: string | null;
    alt: string | null;
  }> | null;
}>;
// Variable: blogQuery
// Query: *[_type == "blogs" && slug.current == $blog][0]{  _id,  blogTitle,  slug,  blogContentText,  "blogImages": blogImages[] {    "imageUrl": image.asset->url,    alt,  },}
export type BlogQueryResult = {
  _id: string;
  blogTitle: string | null;
  slug: Slug | null;
  blogContentText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  blogImages: Array<{
    imageUrl: string | null;
    alt: string | null;
  }> | null;
} | null;
// Variable: lesArchivesVivantesQuery
// Query: *[_type == "lesArchivesVivantes"][0]
export type LesArchivesVivantesQueryResult = {
  _id: string;
  _type: "lesArchivesVivantes";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  linkToVimeo?: string;
  linkToPodcast?: string;
} | null;
// Variable: pagesContentQuery
// Query: *[_type == "pages" && slug.current == $pages][0] {  _id,  title,  "slug": slug.current,  "contentModulde": content[]{    _id,    _key,    _type,    titleBlock,    "contenBlock": block[]{      // ...,      _type,        _id,  _key,  "richtext": text[],        _id,  "richTextTitle": title,  "richtextTitleText": text[],        _id,  "imageTitle": title,  "imageUrl": image.asset->url,        _id,  "multiImages": images[] {        "imageUrl": image.asset->url,        alt,      },        _id,  "linkLabel": label,  // external  external,  // internal  "internal": internal->{    _id,    _type,    title,    "slug": slug.current,  },  "mail": mail,        _id,  "isDisplayed": event.isDisplayed,  "lastEventLabel": event.title,  "goToAllEvents": event.ctaToEvents,        _id,  "creationArchivesTitle": intro[],  "creationArchivesArchive": archive[] {    title,    description[],    status,    },        _id,  "customHtml": html,  "codeTitle": codeTitle,  "isAddFiles": isAddFiles,  "fileGroup": fileGroup[] {    title,    files[] {      asset->,      },      },        _id,  title,  "fileUrl": file.asset->url,  "fileName": file.asset->originalFilename,    },  }}
export type PagesContentQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  contentModulde: Array<{
    _id: null;
    _key: string;
    _type: "content";
    titleBlock: string | null;
    contenBlock: Array<
      | {
          _type: "contact-form";
          _id: null;
          _key: string;
          richtext: null;
          richTextTitle: string | null;
          richtextTitleText: null;
          imageTitle: string | null;
          imageUrl: null;
          multiImages: null;
          linkLabel: null;
          external: null;
          internal: null;
          mail: null;
          isDisplayed: null;
          lastEventLabel: null;
          goToAllEvents: null;
          creationArchivesTitle: null;
          creationArchivesArchive: null;
          customHtml: null;
          codeTitle: null;
          isAddFiles: null;
          fileGroup: null;
          title: string | null;
          fileUrl: null;
          fileName: null;
        }
      | {
          _type: "creationArchives";
          _id: null;
          _key: string;
          richtext: null;
          richTextTitle: null;
          richtextTitleText: null;
          imageTitle: null;
          imageUrl: null;
          multiImages: null;
          linkLabel: null;
          external: null;
          internal: null;
          mail: null;
          isDisplayed: null;
          lastEventLabel: null;
          goToAllEvents: null;
          creationArchivesTitle: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              | "blockquote"
              | "h1"
              | "h2"
              | "h3"
              | "h4"
              | "h5"
              | "h6"
              | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }> | null;
          creationArchivesArchive: Array<{
            title: string | null;
            description: Array<{
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?:
                | "blockquote"
                | "h1"
                | "h2"
                | "h3"
                | "h4"
                | "h5"
                | "h6"
                | "normal";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }> | null;
            status: string | null;
          }> | null;
          customHtml: null;
          codeTitle: null;
          isAddFiles: null;
          fileGroup: null;
          title: null;
          fileUrl: null;
          fileName: null;
        }
      | {
          _type: "custom-html";
          _id: null;
          _key: string;
          richtext: null;
          richTextTitle: null;
          richtextTitleText: null;
          imageTitle: null;
          imageUrl: null;
          multiImages: null;
          linkLabel: null;
          external: null;
          internal: null;
          mail: null;
          isDisplayed: null;
          lastEventLabel: null;
          goToAllEvents: null;
          creationArchivesTitle: null;
          creationArchivesArchive: null;
          customHtml: Code | null;
          codeTitle: string | null;
          isAddFiles: boolean | null;
          fileGroup: Array<{
            title: string | null;
            files: Array<{
              asset: {
                _id: string;
                _type: "sanity.fileAsset";
                _createdAt: string;
                _updatedAt: string;
                _rev: string;
                originalFilename?: string;
                label?: string;
                title?: string;
                description?: string;
                altText?: string;
                sha1hash?: string;
                extension?: string;
                mimeType?: string;
                size?: number;
                assetId?: string;
                uploadId?: string;
                path?: string;
                url?: string;
                source?: SanityAssetSourceData;
              } | null;
            }> | null;
          }> | null;
          title: null;
          fileUrl: null;
          fileName: null;
        }
      | {
          _type: "document-file";
          _id: null;
          _key: string;
          richtext: null;
          richTextTitle: string | null;
          richtextTitleText: null;
          imageTitle: string | null;
          imageUrl: null;
          multiImages: null;
          linkLabel: null;
          external: null;
          internal: null;
          mail: null;
          isDisplayed: null;
          lastEventLabel: null;
          goToAllEvents: null;
          creationArchivesTitle: null;
          creationArchivesArchive: null;
          customHtml: null;
          codeTitle: null;
          isAddFiles: null;
          fileGroup: null;
          title: string | null;
          fileUrl: string | null;
          fileName: string | null;
        }
      | {
          _type: "lastEvent";
          _id: null;
          _key: string;
          richtext: null;
          richTextTitle: null;
          richtextTitleText: null;
          imageTitle: null;
          imageUrl: null;
          multiImages: null;
          linkLabel: null;
          external: null;
          internal: null;
          mail: null;
          isDisplayed: boolean | null;
          lastEventLabel: string | null;
          goToAllEvents: string | null;
          creationArchivesTitle: null;
          creationArchivesArchive: null;
          customHtml: null;
          codeTitle: null;
          isAddFiles: null;
          fileGroup: null;
          title: null;
          fileUrl: null;
          fileName: null;
        }
      | {
          _type: "link";
          _id: null;
          _key: string;
          richtext: null;
          richTextTitle: null;
          richtextTitleText: null;
          imageTitle: null;
          imageUrl: null;
          multiImages: null;
          linkLabel: string | null;
          external: string | null;
          internal: {
            _id: string;
            _type: "pages";
            title: string | null;
            slug: string | null;
          } | null;
          mail: string | null;
          isDisplayed: null;
          lastEventLabel: null;
          goToAllEvents: null;
          creationArchivesTitle: null;
          creationArchivesArchive: null;
          customHtml: null;
          codeTitle: null;
          isAddFiles: null;
          fileGroup: null;
          title: null;
          fileUrl: null;
          fileName: null;
        }
      | {
          _type: "multi-images";
          _id: null;
          _key: string;
          richtext: null;
          richTextTitle: string | null;
          richtextTitleText: null;
          imageTitle: string | null;
          imageUrl: null;
          multiImages: Array<{
            imageUrl: string | null;
            alt: string | null;
          }> | null;
          linkLabel: null;
          external: null;
          internal: null;
          mail: null;
          isDisplayed: null;
          lastEventLabel: null;
          goToAllEvents: null;
          creationArchivesTitle: null;
          creationArchivesArchive: null;
          customHtml: null;
          codeTitle: null;
          isAddFiles: null;
          fileGroup: null;
          title: string | null;
          fileUrl: null;
          fileName: null;
        }
      | {
          _type: "richtext";
          _id: null;
          _key: string;
          richtext: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              | "blockquote"
              | "h1"
              | "h2"
              | "h3"
              | "h4"
              | "h5"
              | "h6"
              | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }> | null;
          richTextTitle: null;
          richtextTitleText: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              | "blockquote"
              | "h1"
              | "h2"
              | "h3"
              | "h4"
              | "h5"
              | "h6"
              | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }> | null;
          imageTitle: null;
          imageUrl: null;
          multiImages: null;
          linkLabel: null;
          external: null;
          internal: null;
          mail: null;
          isDisplayed: null;
          lastEventLabel: null;
          goToAllEvents: null;
          creationArchivesTitle: null;
          creationArchivesArchive: null;
          customHtml: null;
          codeTitle: null;
          isAddFiles: null;
          fileGroup: null;
          title: null;
          fileUrl: null;
          fileName: null;
        }
      | {
          _type: "richTextAndTitle";
          _id: null;
          _key: string;
          richtext: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              | "blockquote"
              | "h1"
              | "h2"
              | "h3"
              | "h4"
              | "h5"
              | "h6"
              | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }> | null;
          richTextTitle: string | null;
          richtextTitleText: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              | "blockquote"
              | "h1"
              | "h2"
              | "h3"
              | "h4"
              | "h5"
              | "h6"
              | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }> | null;
          imageTitle: string | null;
          imageUrl: null;
          multiImages: null;
          linkLabel: null;
          external: null;
          internal: null;
          mail: null;
          isDisplayed: null;
          lastEventLabel: null;
          goToAllEvents: null;
          creationArchivesTitle: null;
          creationArchivesArchive: null;
          customHtml: null;
          codeTitle: null;
          isAddFiles: null;
          fileGroup: null;
          title: string | null;
          fileUrl: null;
          fileName: null;
        }
      | {
          _type: "single-image";
          _id: null;
          _key: string;
          richtext: null;
          richTextTitle: string | null;
          richtextTitleText: null;
          imageTitle: string | null;
          imageUrl: string | null;
          multiImages: null;
          linkLabel: null;
          external: null;
          internal: null;
          mail: null;
          isDisplayed: null;
          lastEventLabel: null;
          goToAllEvents: null;
          creationArchivesTitle: null;
          creationArchivesArchive: null;
          customHtml: null;
          codeTitle: null;
          isAddFiles: null;
          fileGroup: null;
          title: string | null;
          fileUrl: null;
          fileName: null;
        }
    > | null;
  }> | null;
} | null;
